name: Release

on:
  repository_dispatch:
    types: [deploy-success]
  deployment_status:

jobs:
  release:
    name: Release
    if: |
      github.event_name == 'repository_dispatch' ||
      (github.event_name == 'deployment_status' &&
       github.event.deployment_status.state == 'success' &&
       github.event.deployment.environment == 'Production')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup project dependencies
        uses: ./.github/actions/install

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release
